#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
把 libdbc.so 转成 C 内存数组（launcher/so_embed.c / so_embed.h）
供 dbc 启动器静态内嵌。

用法:
  python scripts/embed_so.py <so_path> <out_c> <out_h>
  python scripts/embed_so.py          # 使用默认路径
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SO = ROOT / "outputs" / "arm64-v8a" / "libdbc.so"
DEFAULT_C = ROOT / "launcher" / "so_embed.c"
DEFAULT_H = ROOT / "launcher" / "so_embed.h"


def embed_so(so_path: Path, out_c: Path, out_h: Path, bytes_per_line: int = 16) -> int:
    if not so_path.is_file():
        print(f"[embed] ERROR: so not found: {so_path}", file=sys.stderr)
        return 1

    data = so_path.read_bytes()
    if len(data) < 4 or data[:4] != b"\x7fELF":
        print(f"[embed] ERROR: not a valid ELF: {so_path}", file=sys.stderr)
        return 1

    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_h.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "/* Auto-generated by embed_so.py — do not edit */",
        '#include "so_embed.h"',
        "",
        "const unsigned char dbc_so[] = {",
    ]
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i : i + bytes_per_line]
        lines.append("  " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const unsigned int dbc_so_len = {len(data)};")
    lines.append("")

    out_c.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    out_h.write_text(
        "#ifndef SO_EMBED_H\n"
        "#define SO_EMBED_H\n"
        "#include <stddef.h>\n"
        "extern const unsigned char dbc_so[];\n"
        "extern const unsigned int dbc_so_len;\n"
        "#endif\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"[embed] OK  {so_path}")
    print(f"[embed]   -> {out_c}  ({len(data)} bytes, {out_c.stat().st_size} text)")
    print(f"[embed]   -> {out_h}")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Embed libdbc.so into C byte array")
    p.add_argument("so_path", nargs="?", type=Path, default=DEFAULT_SO)
    p.add_argument("out_c", nargs="?", type=Path, default=DEFAULT_C)
    p.add_argument("out_h", nargs="?", type=Path, default=DEFAULT_H)
    args = p.parse_args(argv)
    return embed_so(args.so_path, args.out_c, args.out_h)


if __name__ == "__main__":
    raise SystemExit(main())
